prettier, правки Умяра и кнопка копирования
dreamDevTeamx/website pull request #3
Opened 2022-01-19 12:57 UTC by SeryiBaran

2022-01-19 13:21 UTC, umyar requested changes

2022-01-19 13:21 UTC, umyar commented on public/js/react-course.js
> +function CopyToClipboard(arg) {
функции, как и переменные, всегда именуются с маленькой буквы

2022-01-19 13:21 UTC, umyar commented on public/js/react-course.js
> +  var aux = document.createElement('input');
var? 🙄
aux? Что значит aux? Лучше написать input, если aux - просто скопированное имя.

2022-01-19 13:21 UTC, umyar commented on public/js/react-course.js
> +let isLinkEmail = false;
Почему переменная объявлена вне цикла? Она нужна снаружи?
Почему бы на каждой итерации цикла прямо внутри него (цикла) не создавать переменную?

`const isEmailLink = ...;`

2022-01-19 13:21 UTC, umyar commented on public/js/react-course.js
> +const linksForCopyFunc = 'CopyToClipboard(this.previousElementSibling.href)';
Перед второй строкой поставь TODO.

`// TODO: try to simplify in future`

2022-01-19 13:28 UTC, SeryiBaran commented on public/js/react-course.js
> +  var aux = document.createElement('input');
а, я с инета копировал, забыл переименовать

2022-01-19 13:31 UTC, SeryiBaran commented on public/js/react-course.js
> +function CopyToClipboard(arg) {
Готово, скоро закоммичу

2022-01-19 13:31 UTC, SeryiBaran commented on public/js/react-course.js
> +  var aux = document.createElement('input');
Готово, скоро закоммичу

2022-01-19 13:32 UTC, SeryiBaran commented on public/js/react-course.js
> +let isLinkEmail = false;
Переделал, скоро закоммичу

2022-01-19 13:32 UTC, SeryiBaran commented on public/js/react-course.js
> +const linksForCopyFunc = 'CopyToClipboard(this.previousElementSibling.href)';
Написал, скоро закоммичу

2022-01-19 13:36 UTC, SeryiBaran commented
Вроде все

2022-01-20 17:43 UTC, umyar approved these changes

2022-01-20 17:43 UTC, merged